export const questions = [
    // Level 1
  {
    level: 1,
    questionText: 'What is the capital of France?',
    questionMode: 'Easy',
    answerOptions: [
      { answerText: 'New York', isCorrect: false, answerImage: require('../assets/newyork.jpg') },
      { answerText: 'London', isCorrect: false, answerImage: require('../assets/london.jpg') },
      { answerText: 'Paris', isCorrect: true, answerImage: require('../assets/paris.jpg') },
      { answerText: 'Dublin', isCorrect: false, answerImage: require('../assets/dublin.jpg') },
    ],
  },
  {
    level: 1,
    questionText: 'Which planet is known as the Red Planet?',
    questionMode: 'Easy',
    answerOptions: [
      { answerText: 'Earth', isCorrect: false, answerImage: require('../assets/earth.jpg') },
      { answerText: 'Mars', isCorrect: true, answerImage: require('../assets/mars.jpg') },
      { answerText: 'Jupiter', isCorrect: false, answerImage: require('../assets/jupiter.jpg') },
      { answerText: 'Saturn', isCorrect: false, answerImage: require('../assets/saturn.jpg') },
    ],
  },
    {
      level: 1,
      questionText: 'What is the largest ocean on Earth?',
      questionMode: 'Easy',
      answerOptions: [
        { answerText: 'Atlantic Ocean', isCorrect: false, answerImage: require('../assets/atlantic_ocean.jpg')},
        { answerText: 'Indian Ocean', isCorrect: false, answerImage:require('../assets/indian_ocean.jpg')},
        { answerText: 'Arctic Ocean', isCorrect: false, answerImage:require('../assets/arctic_ocean.jpg') },
        { answerText: 'Pacific Ocean', isCorrect: true, answerImage: require('../assets/pacific_ocean.jpg') },
      ],
    },
    {
      level: 1,
      questionText: 'Which country is known as the Land of the Rising Sun?',
      questionMode: 'Easy',
      answerOptions: [
        { answerText: 'China', isCorrect: false, answerImage: '../assets/china.jpg' },
        { answerText: 'Japan', isCorrect: true, answerImage: '../assets/japan.jpg' },
        { answerText: 'South Korea', isCorrect: false, answerImage: '../assets/south_korea.jpg' },
        { answerText: 'Thailand', isCorrect: false, answerImage: '../assets/thailand.jpg' },
      ],
    },
    {
      level: 1,
      questionText: 'Who wrote the play "Romeo and Juliet"?',
      questionMode: 'Easy',
      answerOptions: [
        { answerText: 'William Shakespeare', isCorrect: true, answerImage: '../assets/william_shakespeare.jpg' },
        { answerText: 'Charles Dickens', isCorrect: false, answerImage: '../assets/charles_dicken.jpg' },
        { answerText: 'Jane Austen', isCorrect: false, answerImage: '../assets/jane_austen.jpg' },
        { answerText: 'Mark Twain', isCorrect: false, answerImage: '../assets/mark_twain.jpg' },
      ],
    },
    {
      level: 1,
      questionText: 'What is the chemical symbol for water?',
      questionMode: 'Easy',
      answerOptions: [
        { answerText: 'H2O', isCorrect: true , answerImage: '../assets/h20.jpg' },
        { answerText: 'CO2', isCorrect: false, answerImage: '../assets/co2.jpg' },
        { answerText: 'O2', isCorrect: false, answerImage: '../assets/o2.jpg' },
        { answerText: 'NaCl', isCorrect: false, answerImage: '../assets/nacl.jpg' },
      ],
    },
    {
      level: 1,
      questionText: 'What is the smallest country in the world?',
      questionMode: 'Easy',
      answerOptions: [
        { answerText: 'Monaco', isCorrect: false, answerImage: '../assets/monaco.jpg' },
        { answerText: 'Vatican City', isCorrect: true, answerImage: '../assets/vatican_city.jpg' },
        { answerText: 'San Marino', isCorrect: false, answerImage: '../assets/san_marino.jpg' },
        { answerText: 'Liechtenstein', isCorrect: false, answerImage: '../assets/liechtenstein.jpg' },
      ],
    },
    {
      level: 1,
      questionText: 'What is the main ingredient in guacamole?',
      questionMode: 'Easy',
      answerOptions: [
        { answerText: 'Tomato', isCorrect: false, answerImage: '../assets/liechtenstein.jpg' },
        { answerText: 'Onion', isCorrect: false, answerImage: '../assets/liechtenstein.jpg' },
        { answerText: 'Avocado', isCorrect: true, answerImage: '../assets/liechtenstein.jpg' },
        { answerText: 'Cucumber', isCorrect: false, answerImage: '../assets/liechtenstein.jpg' },
      ],
    },
    {
      level: 1,
      questionText: 'How many continents are there on Earth?',
      questionMode: 'Easy',
      answerOptions: [
        { answerText: '5', isCorrect: false },
        { answerText: '6', isCorrect: false },
        { answerText: '7', isCorrect: true },
        { answerText: '8', isCorrect: false },
      ],
    },
    {
      level: 1,
      questionText: 'Which animal is known as the King of the Jungle?',
      questionMode: 'Easy',
      answerOptions: [
        { answerText: 'Tiger', isCorrect: false, answerImage: '../assets/tiger.jpg' },
        { answerText: 'Elephant', isCorrect: false, answerImage: '../assets/elephant.jpg' },
        { answerText: 'Lion', isCorrect: true, answerImage: '../assets/lion.jpg' },
        { answerText: 'Giraffe', isCorrect: false, answerImage: '../assets/giraffe.jpg' },
      ],
    },
    {
      level: 1,
      questionText: 'Who discovered penicillin?',
      questionMode: 'Normal',
      answerOptions: [
        { answerText: 'Marie Curie', isCorrect: false },
        { answerText: 'Alexander Fleming', isCorrect: true },
        { answerText: 'Isaac Newton', isCorrect: false },
        { answerText: 'Albert Einstein', isCorrect: false },
      ],
    },
    {
      level: 1,
      questionText: 'What is the largest planet in our solar system?',
      questionMode: 'Normal',
      answerOptions: [
        { answerText: 'Earth', isCorrect: false },
        { answerText: 'Jupiter', isCorrect: true },
        { answerText: 'Saturn', isCorrect: false },
        { answerText: 'Neptune', isCorrect: false },
      ],
    },
    {
      level: 1,
      questionText: 'Which country is home to the kangaroo?',
      questionMode: 'Normal',
      answerOptions: [
        { answerText: 'India', isCorrect: false },
        { answerText: 'Australia', isCorrect: true },
        { answerText: 'Brazil', isCorrect: false },
        { answerText: 'South Africa', isCorrect: false },
      ],
    },
    {
      level: 1,
      questionText: 'What is the main ingredient in traditional paella?',
      questionMode: 'Normal',
      answerOptions: [
        { answerText: 'Pasta', isCorrect: false },
        { answerText: 'Rice', isCorrect: true },
        { answerText: 'Bread', isCorrect: false },
        { answerText: 'Potato', isCorrect: false },
      ],
    },
    {
      level: 1,
      questionText: 'Which country gifted the Statue of Liberty to the USA?',
      questionMode: 'Normal',
      answerOptions: [
        { answerText: 'France', isCorrect: true },
        { answerText: 'Spain', isCorrect: false },
        { answerText: 'Germany', isCorrect: false },
        { answerText: 'Italy', isCorrect: false },
      ],
    },
    {
      level: 1,
      questionText: 'What is the hardest natural substance on Earth?',
      questionMode: 'Normal',
      answerOptions: [
        { answerText: 'Gold', isCorrect: false },
        { answerText: 'Iron', isCorrect: false },
        { answerText: 'Diamond', isCorrect: true },
        { answerText: 'Platinum', isCorrect: false },
      ],
    },
    {
      level: 1,
      questionText: 'Which planet has the most moons?',
      questionMode: 'Normal',
      answerOptions: [
        { answerText: 'Mars', isCorrect: false },
        { answerText: 'Jupiter', isCorrect: false },
        { answerText: 'Saturn', isCorrect: true },
        { answerText: 'Uranus', isCorrect: false },
      ],
    },
    {
      level: 1,
      questionText: 'What is the largest island in the world?',
      questionMode: 'Normal',
      answerOptions: [
        { answerText: 'Greenland', isCorrect: true },
        { answerText: 'New Guinea', isCorrect: false },
        { answerText: 'Borneo', isCorrect: false },
        { answerText: 'Madagascar', isCorrect: false },
      ],
    },
    {
      level: 1,
      questionText: 'Who developed the theory of relativity?',
      questionMode: 'Normal',
      answerOptions: [
        { answerText: 'Isaac Newton', isCorrect: false },
        { answerText: 'Albert Einstein', isCorrect: true },
        { answerText: 'Nikola Tesla', isCorrect: false },
        { answerText: 'Galileo Galilei', isCorrect: false },
      ],
    },
    {
      level: 1,
      questionText: 'What is the smallest bone in the human body?',
      questionMode: 'Normal',
      answerOptions: [
        { answerText: 'Femur', isCorrect: false },
        { answerText: 'Stapes', isCorrect: true },
        { answerText: 'Humerus', isCorrect: false },
        { answerText: 'Tibia', isCorrect: false },
      ],
    },
    {
      level: 1,
      questionText: 'What is the currency of Brazil?',
      questionMode: 'Normal',
      answerOptions: [
        { answerText: 'Dollar', isCorrect: false },
        { answerText: 'Real', isCorrect: true },
        { answerText: 'Peso', isCorrect: false },
        { answerText: 'Euro', isCorrect: false },
      ],
    },
    {
      level: 1,
      questionText: 'Which element has the chemical symbol Fe?',
      questionMode: 'Normal',
      answerOptions: [
        { answerText: 'Iron', isCorrect: true },
        { answerText: 'Fluorine', isCorrect: false },
        { answerText: 'Francium', isCorrect: false },
        { answerText: 'Fermium', isCorrect: false },
      ],
    },
    {
      level: 1,
      questionText: 'What is the main ingredient in a traditional Japanese soup called miso soup?',
      questionMode: 'Hard',
      answerOptions: [
        { answerText: 'Soy sauce', isCorrect: false },
        { answerText: 'Miso paste', isCorrect: true },
        { answerText: 'Tofu', isCorrect: false },
        { answerText: 'Seaweed', isCorrect: false },
      ],
    },
    {
      level: 1,
      questionText: 'Who was the first woman to win a Nobel Prize?',
      questionMode: 'Hard',
      answerOptions: [
        { answerText: 'Marie Curie', isCorrect: true },
        { answerText: 'Mother Teresa', isCorrect: false },
        { answerText: 'Rosalind Franklin', isCorrect: false },
        { answerText: 'Dorothy Hodgkin', isCorrect: false },
      ],
    },
    {
      level: 1,
      questionText: 'What is the main ingredient in traditional Japanese tempura batter?',
      questionMode: 'Hard',
      answerOptions: [
        { answerText: 'Rice flour', isCorrect: false },
        { answerText: 'Cornstarch', isCorrect: false },
        { answerText: 'All-purpose flour', isCorrect: true },
        { answerText: 'Potato starch', isCorrect: false },
      ],
    },
    {
      level: 1,
      questionText: 'What is the smallest unit of matter?',
      questionMode: 'Hard',
      answerOptions: [
        { answerText: 'Molecule', isCorrect: false },
        { answerText: 'Atom', isCorrect: true },
        { answerText: 'Electron', isCorrect: false },
        { answerText: 'Proton', isCorrect: false },
      ],
    },
    {
      level: 1,
      questionText: 'What is the capital of Iceland?',
      questionMode: 'Hard',
      answerOptions: [
        { answerText: 'Oslo', isCorrect: false },
        { answerText: 'Helsinki', isCorrect: false },
        { answerText: 'Reykjavik', isCorrect: true },
        { answerText: 'Stockholm', isCorrect: false },
      ],
    },
    {
      level: 1,
      questionText: 'What is the main ingredient in hummus?',
      questionMode: 'Hard',
      answerOptions: [
        { answerText: 'Lentils', isCorrect: false },
        { answerText: 'Chickpeas', isCorrect: true },
        { answerText: 'Black beans', isCorrect: false },
        { answerText: 'Kidney beans', isCorrect: false },
      ],
    },
    {
      level: 1,
      questionText: 'Who is known as the father of modern physics?',
      questionMode: 'Hard',
      answerOptions: [
        { answerText: 'Isaac Newton', isCorrect: true },
        { answerText: 'Albert Einstein', isCorrect: false },
        { answerText: 'Galileo Galilei', isCorrect: false },
        { answerText: 'Niels Bohr', isCorrect: false },
      ],
    },
    {
      level: 1,
      questionText: 'What is the main ingredient in traditional Italian risotto?',
      questionMode: 'Hard',
      answerOptions: [
        { answerText: 'Barley', isCorrect: false },
        { answerText: 'Quinoa', isCorrect: false },
        { answerText: 'Arborio rice', isCorrect: true },
        { answerText: 'Couscous', isCorrect: false },
      ],
    },
    {
      level: 1,
      questionText: 'What is the primary ingredient in traditional Russian borscht?',
      questionMode: 'Hard',
      answerOptions: [
        { answerText: 'Cabbage', isCorrect: false },
        { answerText: 'Carrot', isCorrect: false },
        { answerText: 'Potato', isCorrect: false },
        { answerText: 'Beetroot', isCorrect: true },
      ],
    },
    {
      level: 1,
      questionText: 'What is the main ingredient in traditional Spanish gazpacho?',
      questionMode: 'Hard',
      answerOptions: [
        { answerText: 'Tomato', isCorrect: true },
        { answerText: 'Cucumber', isCorrect: false },
        { answerText: 'Pepper', isCorrect: false },
        { answerText: 'Garlic', isCorrect: false },
      ],
    },
    {
      level: 1,
      questionText: 'What is the primary ingredient in traditional Greek tzatziki?',
      questionMode: 'Hard',
      answerOptions: [
        { answerText: 'Tomato', isCorrect: false },
        { answerText: 'Cucumber', isCorrect: true },
        { answerText: 'Pepper', isCorrect: false },
        { answerText: 'Garlic', isCorrect: false },
      ],
    },
    {
      level: 1,
      questionText: 'What is the main ingredient in traditional Mexican salsa?',
      questionMode: 'Hard',
      answerOptions: [
        { answerText: 'Tomato', isCorrect: true },
        { answerText: 'Cucumber', isCorrect: false },
        { answerText: 'Pepper', isCorrect: false },
        { answerText: 'Garlic', isCorrect: false },
      ],
    },
    {
      level: 1,
      questionText: 'What is the primary ingredient in traditional Middle Eastern falafel?',
      questionMode: 'Hard',
      answerOptions: [
        { answerText: 'Lentils', isCorrect: false },
        { answerText: 'Chickpeas', isCorrect: true },
        { answerText: 'Black beans', isCorrect: false },
        { answerText: 'Kidney beans', isCorrect: false },
      ],
    },
    {
      level: 1,
      questionText: 'What is the main ingredient in traditional Thai green curry?',
      questionMode: 'Hard',
      answerOptions: [
        { answerText: 'Chicken', isCorrect: false },
        { answerText: 'Beef', isCorrect: false },
        { answerText: 'Pork', isCorrect: false },
        { answerText: 'Coconut milk', isCorrect: true },
      ],
    },
    // Level 2
    // Add 30 questions for Level 2 here following the same pattern
    {
      level: 2,
      questionText: 'What is the capital of Italy?',
      questionMode: 'Easy',
      answerOptions: [
        { answerText: 'Rome', isCorrect: true },
        { answerText: 'Milan', isCorrect: false },
        { answerText: 'Naples', isCorrect: false },
        { answerText: 'Venice', isCorrect: false },
      ],
    },
    {
      level: 2,
      questionText: 'Which ocean is the smallest in the world?',
      questionMode: 'Easy',
      answerOptions: [
        { answerText: 'Indian Ocean', isCorrect: false },
        { answerText: 'Pacific Ocean', isCorrect: false },
        { answerText: 'Arctic Ocean', isCorrect: true },
        { answerText: 'Atlantic Ocean', isCorrect: false },
      ],
    },
    {
      level: 2,
      questionText: 'What is the primary language spoken in Brazil?',
      questionMode: 'Easy',
      answerOptions: [
        { answerText: 'Spanish', isCorrect: false },
        { answerText: 'Portuguese', isCorrect: true },
        { answerText: 'French', isCorrect: false },
        { answerText: 'English', isCorrect: false },
      ],
    },
    {
      level: 2,
      questionText: 'Who painted the Mona Lisa?',
      questionMode: 'Easy',
      answerOptions: [
        { answerText: 'Vincent van Gogh', isCorrect: false },
        { answerText: 'Pablo Picasso', isCorrect: false },
        { answerText: 'Leonardo da Vinci', isCorrect: true },
        { answerText: 'Claude Monet', isCorrect: false },
      ],
    },
    {
      level: 2,
      questionText: 'What is the chemical symbol for gold?',
      questionMode: 'Easy',
      answerOptions: [
        { answerText: 'Au', isCorrect: true },
        { answerText: 'Ag', isCorrect: false },
        { answerText: 'Pb', isCorrect: false },
        { answerText: 'Fe', isCorrect: false },
      ],
    },
    {
      level: 2,
      questionText: 'What is the tallest mountain in the world?',
      questionMode: 'Easy',
      answerOptions: [
        { answerText: 'K2', isCorrect: false },
        { answerText: 'Mount Everest', isCorrect: true },
        { answerText: 'Kangchenjunga', isCorrect: false },
        { answerText: 'Lhotse', isCorrect: false },
      ],
    },
    {
      level: 2,
      questionText: 'Which animal is known for its black and white stripes?',
      questionMode: 'Easy',
      answerOptions: [
        { answerText: 'Lion', isCorrect: false },
        { answerText: 'Tiger', isCorrect: false },
        { answerText: 'Zebra', isCorrect: true },
        { answerText: 'Leopard', isCorrect: false },
      ],
    },
    {
      level: 2,
      questionText: 'What is the primary ingredient in a Caesar salad?',
      questionMode: 'Easy',
      answerOptions: [
        { answerText: 'Lettuce', isCorrect: true },
        { answerText: 'Spinach', isCorrect: false },
        { answerText: 'Kale', isCorrect: false },
        { answerText: 'Arugula', isCorrect: false },
      ],
    },
    {
      level: 2,
      questionText: 'How many states are there in the United States?',
      questionMode: 'Easy',
      answerOptions: [
        { answerText: '48', isCorrect: false },
        { answerText: '49', isCorrect: false },
        { answerText: '50', isCorrect: true },
        { answerText: '51', isCorrect: false },
      ],
    },
    {
      level: 2,
      questionText: 'Who is the author of "Harry Potter" series?',
      questionMode: 'Easy',
      answerOptions: [
        { answerText: 'J.R.R. Tolkien', isCorrect: false },
        { answerText: 'J.K. Rowling', isCorrect: true },
        { answerText: 'George R.R. Martin', isCorrect: false },
        { answerText: 'Suzanne Collins', isCorrect: false },
      ],
    },
    {
      level: 2,
      questionText: 'What is the largest desert in the world?',
      questionMode: 'Normal',
      answerOptions: [
        { answerText: 'Sahara Desert', isCorrect: false },
        { answerText: 'Arabian Desert', isCorrect: false },
        { answerText: 'Gobi Desert', isCorrect: false },
        { answerText: 'Antarctic Desert', isCorrect: true },
      ],
    },
    {
      level: 2,
      questionText: 'Who was the first President of the United States?',
      questionMode: 'Normal',
      answerOptions: [
        { answerText: 'Thomas Jefferson', isCorrect: false },
        { answerText: 'Abraham Lincoln', isCorrect: false },
        { answerText: 'George Washington', isCorrect: true },
        { answerText: 'John Adams', isCorrect: false },
      ],
    },
    {
      level: 2,
      questionText: 'What is the speed of light?',
      questionMode: 'Normal',
      answerOptions: [
        { answerText: '300,000 km/s', isCorrect: true },
        { answerText: '150,000 km/s', isCorrect: false },
        { answerText: '450,000 km/s', isCorrect: false },
        { answerText: '600,000 km/s', isCorrect: false },
      ],
    },
    {
      level: 2,
      questionText: 'Which planet is closest to the sun?',
      questionMode: 'Normal',
      answerOptions: [
        { answerText: 'Venus', isCorrect: false },
        { answerText: 'Earth', isCorrect: false },
        { answerText: 'Mercury', isCorrect: true },
        { answerText: 'Mars', isCorrect: false },
      ],
    },
    {
      level: 2,
      questionText: 'What is the main ingredient in a traditional Greek salad?',
      questionMode: 'Normal',
      answerOptions: [
        { answerText: 'Lettuce', isCorrect: false },
        { answerText: 'Tomato', isCorrect: false },
        { answerText: 'Cucumber', isCorrect: true },
        { answerText: 'Onion', isCorrect: false },
      ],
    },
    {
      level: 2,
      questionText: 'What is the currency of Japan?',
      questionMode: 'Normal',
      answerOptions: [
        { answerText: 'Yen', isCorrect: true },
        { answerText: 'Won', isCorrect: false },
        { answerText: 'Dollar', isCorrect: false },
        { answerText: 'Peso', isCorrect: false },
      ],
    },
    {
      level: 2,
      questionText: 'Which element has the atomic number 1?',
      questionMode: 'Normal',
      answerOptions: [
        { answerText: 'Helium', isCorrect: false },
        { answerText: 'Hydrogen', isCorrect: true },
        { answerText: 'Oxygen', isCorrect: false },
        { answerText: 'Carbon', isCorrect: false },
      ],
    },
    {
      level: 2,
      questionText: 'What is the main ingredient in a traditional Italian pizza?',
      questionMode: 'Normal',
      answerOptions: [
        { answerText: 'Mozzarella', isCorrect: true },
        { answerText: 'Cheddar', isCorrect: false },
        { answerText: 'Parmesan', isCorrect: false },
        { answerText: 'Ricotta', isCorrect: false },
      ],
    },
    {
      level: 2,
      questionText: 'Who wrote the novel "1984"?',
      questionMode: 'Normal',
      answerOptions: [
        { answerText: 'Aldous Huxley', isCorrect: false },
        { answerText: 'George Orwell', isCorrect: true },
        { answerText: 'Ray Bradbury', isCorrect: false },
        { answerText: 'J.D. Salinger', isCorrect: false },
      ],
    },
    {
      level: 2,
      questionText: 'What is the main ingredient in a traditional Vietnamese pho?',
      questionMode: 'Normal',
      answerOptions: [
        { answerText: 'Noodles', isCorrect: true },
        { answerText: 'Rice', isCorrect: false },
        { answerText: 'Bread', isCorrect: false },
        { answerText: 'Potato', isCorrect: false },
      ],
    },
    {
      level: 2,
      questionText: 'What is the primary ingredient in traditional Chinese dumplings?',
      questionMode: 'Normal',
      answerOptions: [
        { answerText: 'Chicken', isCorrect: false },
        { answerText: 'Pork', isCorrect: true },
        { answerText: 'Beef', isCorrect: false },
        { answerText: 'Tofu', isCorrect: false },
      ],
    },
    {
      level: 2,
      questionText: 'What is the capital of Canada?',
      questionMode: 'Hard',
      answerOptions: [
        { answerText: 'Toronto', isCorrect: false },
        { answerText: 'Vancouver', isCorrect: false },
        { answerText: 'Montreal', isCorrect: false },
        { answerText: 'Ottawa', isCorrect: true },
      ],
    },
    {
      level: 2,
      questionText: 'Who discovered penicillin?',
      questionMode: 'Hard',
      answerOptions: [
        { answerText: 'Alexander Fleming', isCorrect: true },
        { answerText: 'Louis Pasteur', isCorrect: false },
        { answerText: 'Marie Curie', isCorrect: false },
        { answerText: 'Isaac Newton', isCorrect: false },
      ],
    },
    {
      level: 2,
      questionText: 'What is the largest planet in our solar system?',
      questionMode: 'Hard',
      answerOptions: [
        { answerText: 'Earth', isCorrect: false },
        { answerText: 'Mars', isCorrect: false },
        { answerText: 'Jupiter', isCorrect: true },
        { answerText: 'Saturn', isCorrect: false },
      ],
    },
    {
      level: 2,
      questionText: 'What is the main ingredient in traditional Spanish paella?',
      questionMode: 'Hard',
      answerOptions: [
        { answerText: 'Pasta', isCorrect: false },
        { answerText: 'Rice', isCorrect: true },
        { answerText: 'Bread', isCorrect: false },
        { answerText: 'Potato', isCorrect: false },
      ],
    },
    {
      level: 2,
      questionText: 'Who is known as the father of modern chemistry?',
      questionMode: 'Hard',
      answerOptions: [
        { answerText: 'Albert Einstein', isCorrect: false },
        { answerText: 'Isaac Newton', isCorrect: false },
        { answerText: 'Antoine Lavoisier', isCorrect: true },
        { answerText: 'Niels Bohr', isCorrect: false },
      ],
    },
    {
      level: 2,
      questionText: 'What is the capital of Australia?',
      questionMode: 'Hard',
      answerOptions: [
        { answerText: 'Sydney', isCorrect: false },
        { answerText: 'Melbourne', isCorrect: false },
        { answerText: 'Canberra', isCorrect: true },
        { answerText: 'Brisbane', isCorrect: false },
      ],
    },
    {
      level: 2,
      questionText: 'What is the main ingredient in a traditional French ratatouille?',
      questionMode: 'Hard',
      answerOptions: [
        { answerText: 'Eggplant', isCorrect: true },
        { answerText: 'Carrot', isCorrect: false },
        { answerText: 'Potato', isCorrect: false },
        { answerText: 'Spinach', isCorrect: false },
      ],
    },
    {
      level: 2,
      questionText: 'Who developed the theory of relativity?',
      questionMode: 'Hard',
      answerOptions: [
        { answerText: 'Isaac Newton', isCorrect: false },
        { answerText: 'Galileo Galilei', isCorrect: false },
        { answerText: 'Albert Einstein', isCorrect: true },
        { answerText: 'Stephen Hawking', isCorrect: false },
      ],
    },
    {
      level: 2,
      questionText: 'What is the main ingredient in a traditional Indian curry?',
      questionMode: 'Hard',
      answerOptions: [
        { answerText: 'Rice', isCorrect: false },
        { answerText: 'Curry leaves', isCorrect: false },
        { answerText: 'Spices', isCorrect: true },
        { answerText: 'Bread', isCorrect: false },
      ],
    },
    {
      level: 2,
      questionText: 'What is the primary ingredient in traditional Japanese sushi?',
      questionMode: 'Hard',
      answerOptions: [
        { answerText: 'Fish', isCorrect: false },
        { answerText: 'Rice', isCorrect: true },
        { answerText: 'Noodles', isCorrect: false },
        { answerText: 'Bread', isCorrect: false },
      ],
    },
    {
      level: 2,
      questionText: 'Who wrote the play "Romeo and Juliet"?',
      questionMode: 'Hard',
      answerOptions: [
        { answerText: 'Christopher Marlowe', isCorrect: false },
        { answerText: 'Ben Jonson', isCorrect: false },
        { answerText: 'William Shakespeare', isCorrect: true },
        { answerText: 'John Milton', isCorrect: false },
      ],
    },
    {
      level: 2,
      questionText: 'What is the main ingredient in traditional Lebanese tabbouleh?',
      questionMode: 'Hard',
      answerOptions: [
        { answerText: 'Tomato', isCorrect: false },
        { answerText: 'Bulgur', isCorrect: true },
        { answerText: 'Cucumber', isCorrect: false },
        { answerText: 'Onion', isCorrect: false },
      ],
    },
    // Level 3
    // Add 30 questions for Level 3 here following the same pattern
    {
      level: 3,
      questionText: 'What is the capital of France?',
      questionMode: 'Easy',
      answerOptions: [
        { answerText: 'Berlin', isCorrect: false },
        { answerText: 'Madrid', isCorrect: false },
        { answerText: 'Paris', isCorrect: true },
        { answerText: 'Lisbon', isCorrect: false },
      ],
    },
    {
      level: 3,
      questionText: 'Which planet is known as the Red Planet?',
      questionMode: 'Easy',
      answerOptions: [
        { answerText: 'Venus', isCorrect: false },
        { answerText: 'Mars', isCorrect: true },
        { answerText: 'Jupiter', isCorrect: false },
        { answerText: 'Saturn', isCorrect: false },
      ],
    },
    {
      level: 3,
      questionText: 'What is the largest mammal in the world?',
      questionMode: 'Easy',
      answerOptions: [
        { answerText: 'Elephant', isCorrect: false },
        { answerText: 'Blue Whale', isCorrect: true },
        { answerText: 'Giraffe', isCorrect: false },
        { answerText: 'Hippopotamus', isCorrect: false },
      ],
    },
    {
      level: 3,
      questionText: 'What is the boiling point of water?',
      questionMode: 'Easy',
      answerOptions: [
        { answerText: '90°C', isCorrect: false },
        { answerText: '95°C', isCorrect: false },
        { answerText: '100°C', isCorrect: true },
        { answerText: '105°C', isCorrect: false },
      ],
    },
    {
      level: 3,
      questionText: 'Which country is known for the Great Wall?',
      questionMode: 'Easy',
      answerOptions: [
        { answerText: 'India', isCorrect: false },
        { answerText: 'China', isCorrect: true },
        { answerText: 'Japan', isCorrect: false },
        { answerText: 'South Korea', isCorrect: false },
      ],
    },
    {
      level: 3,
      questionText: 'Who wrote "Pride and Prejudice"?',
      questionMode: 'Easy',
      answerOptions: [
        { answerText: 'Emily Brontë', isCorrect: false },
        { answerText: 'Jane Austen', isCorrect: true },
        { answerText: 'Mary Shelley', isCorrect: false },
        { answerText: 'Charlotte Brontë', isCorrect: false },
      ],
    },
    {
      level: 3,
      questionText: 'What is the main ingredient in traditional Japanese miso soup?',
      questionMode: 'Easy',
      answerOptions: [
        { answerText: 'Soybean paste', isCorrect: true },
        { answerText: 'Chicken broth', isCorrect: false },
        { answerText: 'Beef stock', isCorrect: false },
        { answerText: 'Vegetable broth', isCorrect: false },
      ],
    },
    {
      level: 3,
      questionText: 'Which ocean lies on the east coast of the United States?',
      questionMode: 'Easy',
      answerOptions: [
        { answerText: 'Indian Ocean', isCorrect: false },
        { answerText: 'Pacific Ocean', isCorrect: false },
        { answerText: 'Atlantic Ocean', isCorrect: true },
        { answerText: 'Arctic Ocean', isCorrect: false },
      ],
    },
    {
      level: 3,
      questionText: 'What is the chemical symbol for sodium?',
      questionMode: 'Easy',
      answerOptions: [
        { answerText: 'Na', isCorrect: true },
        { answerText: 'S', isCorrect: false },
        { answerText: 'K', isCorrect: false },
        { answerText: 'N', isCorrect: false },
      ],
    },
    {
      level: 3,
      questionText: 'Who was the first man to walk on the moon?',
      questionMode: 'Easy',
      answerOptions: [
        { answerText: 'Buzz Aldrin', isCorrect: false },
        { answerText: 'Yuri Gagarin', isCorrect: false },
        { answerText: 'Neil Armstrong', isCorrect: true },
        { answerText: 'John Glenn', isCorrect: false },
      ],
    },
    {
      level: 3,
      questionText: 'What is the largest island in the world?',
      questionMode: 'Normal',
      answerOptions: [
        { answerText: 'Borneo', isCorrect: false },
        { answerText: 'Madagascar', isCorrect: false },
        { answerText: 'Greenland', isCorrect: true },
        { answerText: 'New Guinea', isCorrect: false },
      ],
    },
    {
      level: 3,
      questionText: 'Who is the Greek god of the sea?',
      questionMode: 'Normal',
      answerOptions: [
        { answerText: 'Zeus', isCorrect: false },
        { answerText: 'Poseidon', isCorrect: true },
        { answerText: 'Hades', isCorrect: false },
        { answerText: 'Apollo', isCorrect: false },
      ],
    },
    {
      level: 3,
      questionText: 'What is the hardest natural substance on Earth?',
      questionMode: 'Normal',
      answerOptions: [
        { answerText: 'Gold', isCorrect: false },
        { answerText: 'Iron', isCorrect: false },
        { answerText: 'Diamond', isCorrect: true },
        { answerText: 'Platinum', isCorrect: false },
      ],
    },
    {
      level: 3,
      questionText: 'What is the main ingredient in a traditional Mexican guacamole?',
      questionMode: 'Normal',
      answerOptions: [
        { answerText: 'Tomato', isCorrect: false },
        { answerText: 'Avocado', isCorrect: true },
        { answerText: 'Lime', isCorrect: false },
        { answerText: 'Onion', isCorrect: false },
      ],
    },
    {
      level: 3,
      questionText: 'Who painted the ceiling of the Sistine Chapel?',
      questionMode: 'Normal',
      answerOptions: [
        { answerText: 'Leonardo da Vinci', isCorrect: false },
        { answerText: 'Raphael', isCorrect: false },
        { answerText: 'Michelangelo', isCorrect: true },
        { answerText: 'Donatello', isCorrect: false },
      ],
    },
    {
      level: 3,
      questionText: 'What is the main ingredient in a traditional Greek moussaka?',
      questionMode: 'Normal',
      answerOptions: [
        { answerText: 'Potato', isCorrect: false },
        { answerText: 'Eggplant', isCorrect: true },
        { answerText: 'Zucchini', isCorrect: false },
        { answerText: 'Spinach', isCorrect: false },
      ],
    },
    {
      level: 3,
      questionText: 'Who is the author of "Moby-Dick"?',
      questionMode: 'Normal',
      answerOptions: [
        { answerText: 'Herman Melville', isCorrect: true },
        { answerText: 'Mark Twain', isCorrect: false },
        { answerText: 'Nathaniel Hawthorne', isCorrect: false },
        { answerText: 'F. Scott Fitzgerald', isCorrect: false },
      ],
    },
    {
      level: 3,
      questionText: 'Which element is known as the king of chemicals?',
      questionMode: 'Normal',
      answerOptions: [
        { answerText: 'Oxygen', isCorrect: false },
        { answerText: 'Nitrogen', isCorrect: false },
        { answerText: 'Sulfuric Acid', isCorrect: true },
        { answerText: 'Ammonia', isCorrect: false },
      ],
    },
    {
      level: 3,
      questionText: 'What is the capital of Russia?',
      questionMode: 'Normal',
      answerOptions: [
        { answerText: 'St. Petersburg', isCorrect: false },
        { answerText: 'Moscow', isCorrect: true },
        { answerText: 'Kazan', isCorrect: false },
        { answerText: 'Novosibirsk', isCorrect: false },
      ],
    },
    {
      level: 3,
      questionText: 'Who wrote the epic poem "The Odyssey"?',
      questionMode: 'Normal',
      answerOptions: [
        { answerText: 'Homer', isCorrect: true },
        { answerText: 'Virgil', isCorrect: false },
        { answerText: 'Ovid', isCorrect: false },
        { answerText: 'Sophocles', isCorrect: false },
      ],
    },
    {
      level: 3,
      questionText: 'What is the main ingredient in traditional Japanese tempura?',
      questionMode: 'Normal',
      answerOptions: [
        { answerText: 'Rice', isCorrect: false },
        { answerText: 'Bread', isCorrect: false },
        { answerText: 'Batter', isCorrect: true },
        { answerText: 'Noodles', isCorrect: false },
      ],
    },
    {
      level: 3,
      questionText: 'What is the smallest planet in our solar system?',
      questionMode: 'Hard',
      answerOptions: [
        { answerText: 'Venus', isCorrect: false },
        { answerText: 'Mars', isCorrect: false },
        { answerText: 'Mercury', isCorrect: true },
        { answerText: 'Pluto', isCorrect: false },
      ],
    },
    {
      level: 3,
      questionText: 'Who developed the theory of evolution by natural selection?',
      questionMode: 'Hard',
      answerOptions: [
        { answerText: 'Albert Einstein', isCorrect: false },
        { answerText: 'Isaac Newton', isCorrect: false },
        { answerText: 'Charles Darwin', isCorrect: true },
        { answerText: 'Galileo Galilei', isCorrect: false },
      ],
    },
    {
      level: 3,
      questionText: 'What is the main ingredient in traditional Russian borscht?',
      questionMode: 'Hard',
      answerOptions: [
        { answerText: 'Carrot', isCorrect: false },
        { answerText: 'Beetroot', isCorrect: true },
        { answerText: 'Potato', isCorrect: false },
        { answerText: 'Cabbage', isCorrect: false },
      ],
    },
    {
      level: 3,
      questionText: 'Who is known as the father of geometry?',
      questionMode: 'Hard',
      answerOptions: [
        { answerText: 'Pythagoras', isCorrect: false },
        { answerText: 'Euclid', isCorrect: true },
        { answerText: 'Archimedes', isCorrect: false },
        { answerText: 'Plato', isCorrect: false },
      ],
    },
    {
      level: 3,
      questionText: 'What is the main ingredient in traditional Italian risotto?',
      questionMode: 'Hard',
      answerOptions: [
        { answerText: 'Pasta', isCorrect: false },
        { answerText: 'Rice', isCorrect: true },
        { answerText: 'Bread', isCorrect: false },
        { answerText: 'Potato', isCorrect: false },
      ],
    },
    {
      level: 3,
      questionText: 'Who was the first woman to win a Nobel Prize?',
      questionMode: 'Hard',
      answerOptions: [
        { answerText: 'Marie Curie', isCorrect: true },
        { answerText: 'Rosalind Franklin', isCorrect: false },
        { answerText: 'Jane Goodall', isCorrect: false },
        { answerText: 'Ada Lovelace', isCorrect: false },
      ],
    },
    {
      level: 3,
      questionText: 'What is the main ingredient in traditional Chinese tofu?',
      questionMode: 'Hard',
      answerOptions: [
        { answerText: 'Rice', isCorrect: false },
        { answerText: 'Soybeans', isCorrect: true },
        { answerText: 'Wheat', isCorrect: false },
        { answerText: 'Corn', isCorrect: false },
      ],
    },
    {
      level: 3,
      questionText: 'Who discovered the law of universal gravitation?',
      questionMode: 'Hard',
      answerOptions: [
        { answerText: 'Galileo Galilei', isCorrect: false },
        { answerText: 'Albert Einstein', isCorrect: false },
        { answerText: 'Isaac Newton', isCorrect: true },
        { answerText: 'Johannes Kepler', isCorrect: false },
      ],
    },
    {
      level: 3,
      questionText: 'What is the main ingredient in traditional Spanish gazpacho?',
      questionMode: 'Hard',
      answerOptions: [
        { answerText: 'Tomato', isCorrect: true },
        { answerText: 'Potato', isCorrect: false },
        { answerText: 'Carrot', isCorrect: false },
        { answerText: 'Spinach', isCorrect: false },
      ],
    },
    {
      level: 3,
      questionText: 'Who was the first president of the United States?',
      questionMode: 'Hard',
      answerOptions: [
        { answerText: 'Thomas Jefferson', isCorrect: false },
        { answerText: 'John Adams', isCorrect: false },
        { answerText: 'George Washington', isCorrect: true },
        { answerText: 'James Madison', isCorrect: false },
      ],
    },
    {
      level: 3,
      questionText: 'What is the main ingredient in traditional Indian biryani?',
      questionMode: 'Hard',
      answerOptions: [
        { answerText: 'Bread', isCorrect: false },
        { answerText: 'Rice', isCorrect: true },
        { answerText: 'Noodles', isCorrect: false },
        { answerText: 'Potato', isCorrect: false },
      ],
    },
    {
      level: 3,
      questionText: 'Who wrote the play "Hamlet"?',
      questionMode: 'Hard',
      answerOptions: [
        { answerText: 'Christopher Marlowe', isCorrect: false },
        { answerText: 'Ben Jonson', isCorrect: false },
        { answerText: 'William Shakespeare', isCorrect: true },
        { answerText: 'John Milton', isCorrect: false },
      ],
    },
    {
      level: 3,
      questionText: 'What is the main ingredient in traditional Lebanese kibbeh?',
      questionMode: 'Hard',
      answerOptions: [
        { answerText: 'Tomato', isCorrect: false },
        { answerText: 'Bulgur', isCorrect: true },
        { answerText: 'Cucumber', isCorrect: false },
        { answerText: 'Onion', isCorrect: false },
      ],
    },
    // Level 4
    // Add 30 questions for Level 4 here following the same pattern
    {
        level: 4,
        questionText: 'What is the largest planet in our solar system?',
        questionMode: 'Easy',
        answerOptions: [
            { answerText: 'Earth', isCorrect: false },
            { answerText: 'Mars', isCorrect: false },
            { answerText: 'Jupiter', isCorrect: true },
            { answerText: 'Saturn', isCorrect: false },
        ],
    },
    {
        level: 4,
        questionText: 'Who wrote "Romeo and Juliet"?',
        questionMode: 'Easy',
        answerOptions: [
            { answerText: 'Mark Twain', isCorrect: false },
            { answerText: 'William Shakespeare', isCorrect: true },
            { answerText: 'Jane Austen', isCorrect: false },
            { answerText: 'Charles Dickens', isCorrect: false },
        ],
    },
    {
        level: 4,
        questionText: 'What is the chemical symbol for gold?',
        questionMode: 'Easy',
        answerOptions: [
            { answerText: 'Au', isCorrect: true },
            { answerText: 'Ag', isCorrect: false },
            { answerText: 'Gd', isCorrect: false },
            { answerText: 'Pb', isCorrect: false },
        ],
    },
    {
        level: 4,
        questionText: 'What is the tallest mountain in the world?',
        questionMode: 'Easy',
        answerOptions: [
            { answerText: 'K2', isCorrect: false },
            { answerText: 'Mount Everest', isCorrect: true },
            { answerText: 'Kangchenjunga', isCorrect: false },
            { answerText: 'Lhotse', isCorrect: false },
        ],
    },
    {
        level: 4,
        questionText: 'Which country is famous for the Eiffel Tower?',
        questionMode: 'Easy',
        answerOptions: [
            { answerText: 'Spain', isCorrect: false },
            { answerText: 'Italy', isCorrect: false },
            { answerText: 'France', isCorrect: true },
            { answerText: 'Germany', isCorrect: false },
        ],
    },
    {
        level: 4,
        questionText: 'What is the currency of Japan?',
        questionMode: 'Easy',
        answerOptions: [
            { answerText: 'Yuan', isCorrect: false },
            { answerText: 'Won', isCorrect: false },
            { answerText: 'Yen', isCorrect: true },
            { answerText: 'Dollar', isCorrect: false },
        ],
    },
    {
        level: 4,
        questionText: 'Who is the author of "1984"?',
        questionMode: 'Easy',
        answerOptions: [
            { answerText: 'George Orwell', isCorrect: true },
            { answerText: 'Aldous Huxley', isCorrect: false },
            { answerText: 'Ray Bradbury', isCorrect: false },
            { answerText: 'J.D. Salinger', isCorrect: false },
        ],
    },
    {
        level: 4,
        questionText: 'What is the main ingredient in a traditional Spanish paella?',
        questionMode: 'Easy',
        answerOptions: [
            { answerText: 'Potato', isCorrect: false },
            { answerText: 'Rice', isCorrect: true },
            { answerText: 'Noodles', isCorrect: false },
            { answerText: 'Bread', isCorrect: false },
        ],
    },
    {
        level: 4,
        questionText: 'Which element has the chemical symbol "O"?',
        questionMode: 'Easy',
        answerOptions: [
            { answerText: 'Osmium', isCorrect: false },
            { answerText: 'Oxygen', isCorrect: true },
            { answerText: 'Oganesson', isCorrect: false },
            { answerText: 'Oxide', isCorrect: false },
        ],
    },
    {
        level: 4,
        questionText: 'What is the capital of Italy?',
        questionMode: 'Easy',
        answerOptions: [
            { answerText: 'Venice', isCorrect: false },
            { answerText: 'Florence', isCorrect: false },
            { answerText: 'Rome', isCorrect: true },
            { answerText: 'Milan', isCorrect: false },
        ],
    },
    {
        level: 4,
        questionText: 'What is the smallest country in the world by area?',
        questionMode: 'Normal',
        answerOptions: [
            { answerText: 'Monaco', isCorrect: false },
            { answerText: 'Nauru', isCorrect: false },
            { answerText: 'Vatican City', isCorrect: true },
            { answerText: 'San Marino', isCorrect: false },
        ],
    },
    {
        level: 4,
        questionText: 'What is the speed of light?',
        questionMode: 'Normal',
        answerOptions: [
            { answerText: '300,000 km/s', isCorrect: true },
            { answerText: '150,000 km/s', isCorrect: false },
            { answerText: '450,000 km/s', isCorrect: false },
            { answerText: '600,000 km/s', isCorrect: false },
        ],
    },
    {
        level: 4,
        questionText: 'Who painted "The Starry Night"?',
        questionMode: 'Normal',
        answerOptions: [
            { answerText: 'Claude Monet', isCorrect: false },
            { answerText: 'Pablo Picasso', isCorrect: false },
            { answerText: 'Vincent van Gogh', isCorrect: true },
            { answerText: 'Salvador Dalí', isCorrect: false },
        ],
    },
    {
        level: 4,
        questionText: 'Which gas is most abundant in the Earth\'s atmosphere?',
        questionMode: 'Normal',
        answerOptions: [
            { answerText: 'Oxygen', isCorrect: false },
            { answerText: 'Carbon Dioxide', isCorrect: false },
            { answerText: 'Nitrogen', isCorrect: true },
            { answerText: 'Hydrogen', isCorrect: false },
        ],
    },
    {
        level: 4,
        questionText: 'Who wrote "The Great Gatsby"?',
        questionMode: 'Normal',
        answerOptions: [
            { answerText: 'Ernest Hemingway', isCorrect: false },
            { answerText: 'F. Scott Fitzgerald', isCorrect: true },
            { answerText: 'John Steinbeck', isCorrect: false },
            { answerText: 'William Faulkner', isCorrect: false },
        ],
    },
    {
        level: 4,
        questionText: 'What is the main ingredient in hummus?',
        questionMode: 'Normal',
        answerOptions: [
            { answerText: 'Lentils', isCorrect: false },
            { answerText: 'Chickpeas', isCorrect: true },
            { answerText: 'Kidney beans', isCorrect: false },
            { answerText: 'Black beans', isCorrect: false },
        ],
    },
    {
        level: 4,
        questionText: 'What is the hardest rock?',
        questionMode: 'Normal',
        answerOptions: [
            { answerText: 'Granite', isCorrect: false },
            { answerText: 'Marble', isCorrect: false },
            { answerText: 'Diamond', isCorrect: true },
            { answerText: 'Quartz', isCorrect: false },
        ],
    },
    {
        level: 4,
        questionText: 'Who is known as the "Father of Computers"?',
        questionMode: 'Normal',
        answerOptions: [
            { answerText: 'Alan Turing', isCorrect: false },
            { answerText: 'Bill Gates', isCorrect: false },
            { answerText: 'Charles Babbage', isCorrect: true },
            { answerText: 'Steve Jobs', isCorrect: false },
        ],
    },
    {
        level: 4,
        questionText: 'What is the main ingredient in traditional Italian pesto?',
        questionMode: 'Normal',
        answerOptions: [
            { answerText: 'Basil', isCorrect: true },
            { answerText: 'Oregano', isCorrect: false },
            { answerText: 'Parsley', isCorrect: false },
            { answerText: 'Rosemary', isCorrect: false },
        ],
    },
    {
        level: 4,
        questionText: 'What is the chemical formula for water?',
        questionMode: 'Normal',
        answerOptions: [
            { answerText: 'H2O', isCorrect: true },
            { answerText: 'CO2', isCorrect: false },
            { answerText: 'O2', isCorrect: false },
            { answerText: 'H2', isCorrect: false },
        ],
    },
    {
        level: 4,
        questionText: 'Who is the author of "The Catcher in the Rye"?',
        questionMode: 'Normal',
        answerOptions: [
            { answerText: 'F. Scott Fitzgerald', isCorrect: false },
            { answerText: 'Harper Lee', isCorrect: false },
            { answerText: 'J.D. Salinger', isCorrect: true },
            { answerText: 'Mark Twain', isCorrect: false },
        ],
    },
    {
        level: 4,
        questionText: 'Who developed the theory of relativity?',
        questionMode: 'Hard',
        answerOptions: [
            { answerText: 'Isaac Newton', isCorrect: false },
            { answerText: 'Albert Einstein', isCorrect: true },
            { answerText: 'Niels Bohr', isCorrect: false },
            { answerText: 'Galileo Galilei', isCorrect: false },
        ],
    },
    {
        level: 4,
        questionText: 'What is the main ingredient in traditional Japanese miso soup?',
        questionMode: 'Hard',
        answerOptions: [
            { answerText: 'Soybeans', isCorrect: true },
            { answerText: 'Tofu', isCorrect: false },
            { answerText: 'Rice', isCorrect: false },
            { answerText: 'Seaweed', isCorrect: false },
        ],
    },
    {
        level: 4,
        questionText: 'Who is known as the "Father of Modern Physics"?',
        questionMode: 'Hard',
        answerOptions: [
            { answerText: 'Albert Einstein', isCorrect: false },
            { answerText: 'Galileo Galilei', isCorrect: true },
            { answerText: 'Isaac Newton', isCorrect: false },
            { answerText: 'Niels Bohr', isCorrect: false },
        ],
    },
    {
        level: 4,
        questionText: 'What is the main ingredient in traditional Greek tzatziki?',
        questionMode: 'Hard',
        answerOptions: [
            { answerText: 'Cucumber', isCorrect: true },
            { answerText: 'Tomato', isCorrect: false },
            { answerText: 'Olives', isCorrect: false },
            { answerText: 'Feta cheese', isCorrect: false },
        ],
    },
    {
        level: 4,
        questionText: 'Who discovered penicillin?',
        questionMode: 'Hard',
        answerOptions: [
            { answerText: 'Louis Pasteur', isCorrect: false },
            { answerText: 'Alexander Fleming', isCorrect: true },
            { answerText: 'Marie Curie', isCorrect: false },
            { answerText: 'Robert Koch', isCorrect: false },
        ],
    },
    {
        level: 4,
        questionText: 'What is the main ingredient in traditional Mexican guacamole?',
        questionMode: 'Hard',
        answerOptions: [
            { answerText: 'Tomato', isCorrect: false },
            { answerText: 'Avocado', isCorrect: true },
            { answerText: 'Corn', isCorrect: false },
            { answerText: 'Beans', isCorrect: false },
        ],
    },
    {
        level: 4,
        questionText: 'Who proposed the heliocentric theory?',
        questionMode: 'Hard',
        answerOptions: [
            { answerText: 'Ptolemy', isCorrect: false },
            { answerText: 'Copernicus', isCorrect: true },
            { answerText: 'Galileo Galilei', isCorrect: false },
            { answerText: 'Isaac Newton', isCorrect: false },
        ],
    },
    {
        level: 4,
        questionText: 'What is the main ingredient in traditional Indian paneer?',
        questionMode: 'Hard',
        answerOptions: [
            { answerText: 'Milk', isCorrect: true },
            { answerText: 'Lentils', isCorrect: false },
            { answerText: 'Chickpeas', isCorrect: false },
            { answerText: 'Rice', isCorrect: false },
        ],
    },
    {
        level: 4,
        questionText: 'Who is known as the "Mother of Modern Physics"?',
        questionMode: 'Hard',
        answerOptions: [
            { answerText: 'Marie Curie', isCorrect: true },
            { answerText: 'Rosalind Franklin', isCorrect: false },
            { answerText: 'Ada Lovelace', isCorrect: false },
            { answerText: 'Lise Meitner', isCorrect: false },
        ],
    },
    {
        level: 4,
        questionText: 'What is the main ingredient in traditional French ratatouille?',
        questionMode: 'Hard',
        answerOptions: [
            { answerText: 'Potato', isCorrect: false },
            { answerText: 'Eggplant', isCorrect: true },
            { answerText: 'Carrot', isCorrect: false },
            { answerText: 'Spinach', isCorrect: false },
        ],
    },
    {
        level: 4,
        questionText: 'Who discovered the law of conservation of mass?',
        questionMode: 'Hard',
        answerOptions: [
            { answerText: 'Antoine Lavoisier', isCorrect: true },
            { answerText: 'Dmitri Mendeleev', isCorrect: false },
            { answerText: 'Joseph Priestley', isCorrect: false },
            { answerText: 'Robert Boyle', isCorrect: false },
        ],
    },
    // Level 5
    // Add 30 questions for Level 5 here following the same pattern
    {
        level: 5,
        questionText: 'What is the capital of France?',
        questionMode: 'Easy',
        answerOptions: [
            { answerText: 'Berlin', isCorrect: false },
            { answerText: 'Madrid', isCorrect: false },
            { answerText: 'Paris', isCorrect: true },
            { answerText: 'Rome', isCorrect: false },
        ],
    },
    {
        level: 5,
        questionText: 'What is the boiling point of water?',
        questionMode: 'Easy',
        answerOptions: [
            { answerText: '90°C', isCorrect: false },
            { answerText: '100°C', isCorrect: true },
            { answerText: '110°C', isCorrect: false },
            { answerText: '120°C', isCorrect: false },
        ],
    },
    {
        level: 5,
        questionText: 'Who is the author of "Harry Potter"?',
        questionMode: 'Easy',
        answerOptions: [
            { answerText: 'J.R.R. Tolkien', isCorrect: false },
            { answerText: 'J.K. Rowling', isCorrect: true },
            { answerText: 'George R.R. Martin', isCorrect: false },
            { answerText: 'Stephen King', isCorrect: false },
        ],
    },
    {
        level: 5,
        questionText: 'What is the currency of the United Kingdom?',
        questionMode: 'Easy',
        answerOptions: [
            { answerText: 'Euro', isCorrect: false },
            { answerText: 'Dollar', isCorrect: false },
            { answerText: 'Pound Sterling', isCorrect: true },
            { answerText: 'Yen', isCorrect: false },
        ],
    },
    {
        level: 5,
        questionText: 'Who painted the "Mona Lisa"?',
        questionMode: 'Easy',
        answerOptions: [
            { answerText: 'Vincent van Gogh', isCorrect: false },
            { answerText: 'Leonardo da Vinci', isCorrect: true },
            { answerText: 'Claude Monet', isCorrect: false },
            { answerText: 'Pablo Picasso', isCorrect: false },
        ],
    },
    {
        level: 5,
        questionText: 'What is the largest ocean on Earth?',
        questionMode: 'Easy',
        answerOptions: [
            { answerText: 'Atlantic Ocean', isCorrect: false },
            { answerText: 'Indian Ocean', isCorrect: false },
            { answerText: 'Arctic Ocean', isCorrect: false },
            { answerText: 'Pacific Ocean', isCorrect: true },
        ],
    },
    {
        level: 5,
        questionText: 'What is the smallest planet in our solar system?',
        questionMode: 'Easy',
        answerOptions: [
            { answerText: 'Earth', isCorrect: false },
            { answerText: 'Venus', isCorrect: false },
            { answerText: 'Mars', isCorrect: false },
            { answerText: 'Mercury', isCorrect: true },
        ],
    },
    {
        level: 5,
        questionText: 'Who discovered gravity?',
        questionMode: 'Easy',
        answerOptions: [
            { answerText: 'Albert Einstein', isCorrect: false },
            { answerText: 'Isaac Newton', isCorrect: true },
            { answerText: 'Galileo Galilei', isCorrect: false },
            { answerText: 'Nikola Tesla', isCorrect: false },
        ],
    },
    {
        level: 5,
        questionText: 'What is the primary language spoken in Brazil?',
        questionMode: 'Easy',
        answerOptions: [
            { answerText: 'Spanish', isCorrect: false },
            { answerText: 'Portuguese', isCorrect: true },
            { answerText: 'French', isCorrect: false },
            { answerText: 'English', isCorrect: false },
        ],
    },
    {
        level: 5,
        questionText: 'What is the hardest natural substance on Earth?',
        questionMode: 'Easy',
        answerOptions: [
            { answerText: 'Gold', isCorrect: false },
            { answerText: 'Iron', isCorrect: false },
            { answerText: 'Diamond', isCorrect: true },
            { answerText: 'Silver', isCorrect: false },
        ],
    },

    // Level 5 - Normal
    {
        level: 5,
        questionText: 'Who developed the polio vaccine?',
        questionMode: 'Normal',
        answerOptions: [
            { answerText: 'Albert Sabin', isCorrect: false },
            { answerText: 'Alexander Fleming', isCorrect: false },
            { answerText: 'Jonas Salk', isCorrect: true },
            { answerText: 'Edward Jenner', isCorrect: false },
        ],
    },
    {
        level: 5,
        questionText: 'What is the chemical symbol for potassium?',
        questionMode: 'Normal',
        answerOptions: [
            { answerText: 'P', isCorrect: false },
            { answerText: 'Pt', isCorrect: false },
            { answerText: 'K', isCorrect: true },
            { answerText: 'Po', isCorrect: false },
        ],
    },
    {
        level: 5,
        questionText: 'What is the longest river in the world?',
        questionMode: 'Normal',
        answerOptions: [
            { answerText: 'Amazon River', isCorrect: false },
            { answerText: 'Yangtze River', isCorrect: false },
            { answerText: 'Mississippi River', isCorrect: false },
            { answerText: 'Nile River', isCorrect: true },
        ],
    },
    {
        level: 5,
        questionText: 'Who wrote "The Odyssey"?',
        questionMode: 'Normal',
        answerOptions: [
            { answerText: 'Homer', isCorrect: true },
            { answerText: 'Virgil', isCorrect: false },
            { answerText: 'Ovid', isCorrect: false },
            { answerText: 'Sophocles', isCorrect: false },
        ],
    },
    {
        level: 5,
        questionText: 'What is the capital of Canada?',
        questionMode: 'Normal',
        answerOptions: [
            { answerText: 'Toronto', isCorrect: false },
            { answerText: 'Vancouver', isCorrect: false },
            { answerText: 'Montreal', isCorrect: false },
            { answerText: 'Ottawa', isCorrect: true },
        ],
    },
    {
        level: 5,
        questionText: 'What element does "O" represent on the periodic table?',
        questionMode: 'Normal',
        answerOptions: [
            { answerText: 'Osmium', isCorrect: false },
            { answerText: 'Oxygen', isCorrect: true },
            { answerText: 'Oganesson', isCorrect: false },
            { answerText: 'Ozone', isCorrect: false },
        ],
    },
    {
        level: 5,
        questionText: 'Who was the first woman to win a Nobel Prize?',
        questionMode: 'Normal',
        answerOptions: [
            { answerText: 'Marie Curie', isCorrect: true },
            { answerText: 'Rosalind Franklin', isCorrect: false },
            { answerText: 'Ada Lovelace', isCorrect: false },
            { answerText: 'Jane Goodall', isCorrect: false },
        ],
    },
    {
        level: 5,
        questionText: 'What is the capital of Australia?',
        questionMode: 'Normal',
        answerOptions: [
            { answerText: 'Sydney', isCorrect: false },
            { answerText: 'Melbourne', isCorrect: false },
            { answerText: 'Canberra', isCorrect: true },
            { answerText: 'Brisbane', isCorrect: false },
        ],
    },
    {
        level: 5,
        questionText: 'What is the most spoken language in the world?',
        questionMode: 'Normal',
        answerOptions: [
            { answerText: 'Spanish', isCorrect: false },
            { answerText: 'English', isCorrect: false },
            { answerText: 'Mandarin Chinese', isCorrect: true },
            { answerText: 'Hindi', isCorrect: false },
        ],
    },
    {
        level: 5,
        questionText: 'What is the largest continent by area?',
        questionMode: 'Normal',
        answerOptions: [
            { answerText: 'Africa', isCorrect: false },
            { answerText: 'Asia', isCorrect: true },
            { answerText: 'North America', isCorrect: false },
            { answerText: 'Europe', isCorrect: false },
        ],
    },

    // Level 5 - Hard
    {
        level: 5,
        questionText: 'Who wrote "Pride and Prejudice"?',
        questionMode: 'Normal',
        answerOptions: [
            { answerText: 'Jane Austen', isCorrect: true },
            { answerText: 'Charlotte Brontë', isCorrect: false },
            { answerText: 'Emily Brontë', isCorrect: false },
            { answerText: 'Mary Shelley', isCorrect: false },
        ],
    },
    {
        level: 5,
        questionText: 'Who developed the theory of relativity?',
        questionMode: 'Normal',
        answerOptions: [
            { answerText: 'Isaac Newton', isCorrect: false },
            { answerText: 'Albert Einstein', isCorrect: true },
            { answerText: 'Niels Bohr', isCorrect: false },
            { answerText: 'Max Planck', isCorrect: false },
        ],
    },
    {
        level: 5,
        questionText: 'What is the chemical symbol for gold?',
        questionMode: 'Normal',
        answerOptions: [
            { answerText: 'Au', isCorrect: true },
            { answerText: 'Ag', isCorrect: false },
            { answerText: 'Pb', isCorrect: false },
            { answerText: 'Fe', isCorrect: false },
        ],
    },
    {
        level: 5,
        questionText: 'Who is known as the "Father of Computers"?',
        questionMode: 'Normal',
        answerOptions: [
            { answerText: 'Charles Babbage', isCorrect: true },
            { answerText: 'Alan Turing', isCorrect: false },
            { answerText: 'John von Neumann', isCorrect: false },
            { answerText: 'Ada Lovelace', isCorrect: false },
        ],
    },
    {
        level: 5,
        questionText: 'What is the square root of 144?',
        questionMode: 'Hard',
        answerOptions: [
            { answerText: '10', isCorrect: false },
            { answerText: '12', isCorrect: true },
            { answerText: '14', isCorrect: false },
            { answerText: '16', isCorrect: false },
        ],
    },
    {
        level: 5,
        questionText: 'What is the chemical formula for table salt?',
        questionMode: 'Hard',
        answerOptions: [
            { answerText: 'NaCl', isCorrect: true },
            { answerText: 'H2O', isCorrect: false },
            { answerText: 'KCl', isCorrect: false },
            { answerText: 'CaCO3', isCorrect: false },
        ],
    },
    {
        level: 5,
        questionText: 'Who is credited with inventing the telephone?',
        questionMode: 'Hard',
        answerOptions: [
            { answerText: 'Alexander Graham Bell', isCorrect: true },
            { answerText: 'Thomas Edison', isCorrect: false },
            { answerText: 'Nikola Tesla', isCorrect: false },
            { answerText: 'Guglielmo Marconi', isCorrect: false },
        ],
    },
    {
        level: 5,
        questionText: 'What year did the Titanic sink?',
        questionMode: 'Hard',
        answerOptions: [
            { answerText: '1910', isCorrect: false },
            { answerText: '1912', isCorrect: true },
            { answerText: '1914', isCorrect: false },
            { answerText: '1916', isCorrect: false },
        ],
    },
    {
        level: 5,
        questionText: 'What is the most abundant gas in the Earth\'s atmosphere?',
        questionMode: 'Hard',
        answerOptions: [
            { answerText: 'Oxygen', isCorrect: false },
            { answerText: 'Carbon Dioxide', isCorrect: false },
            { answerText: 'Nitrogen', isCorrect: true },
            { answerText: 'Argon', isCorrect: false },
        ],
    },
    {
        level: 5,
        questionText: 'Which planet is known as the "Red Planet"?',
        questionMode: 'Hard',
        answerOptions: [
            { answerText: 'Mars', isCorrect: true },
            { answerText: 'Jupiter', isCorrect: false },
            { answerText: 'Saturn', isCorrect: false },
            { answerText: 'Venus', isCorrect: false },
        ],
    },
    {
        level: 5,
        questionText: 'Who was the 16th President of the United States?',
        questionMode: 'Hard',
        answerOptions: [
            { answerText: 'Abraham Lincoln', isCorrect: true },
            { answerText: 'George Washington', isCorrect: false },
            { answerText: 'Thomas Jefferson', isCorrect: false },
            { answerText: 'Andrew Johnson', isCorrect: false },
        ],
    },
    {
        level: 5,
        questionText: 'What is the value of π (pi) to three decimal places?',
        questionMode: 'Hard',
        answerOptions: [
            { answerText: '3.141', isCorrect: true },
            { answerText: '3.142', isCorrect: false },
            { answerText: '3.143', isCorrect: false },
            { answerText: '3.144', isCorrect: false },
        ],
    },
];

